//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeedleworkStore.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NeedleworkStoreEntities : DbContext
    {
        public NeedleworkStoreEntities()
            : base("name=NeedleworkStoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessoryTypes> AccessoryTypes { get; set; }
        public virtual DbSet<AssigningStatuses> AssigningStatuses { get; set; }
        public virtual DbSet<AvailabilityStatuses> AvailabilityStatuses { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Designers> Designers { get; set; }
        public virtual DbSet<Favourities> Favourities { get; set; }
        public virtual DbSet<NeedleworkTypes> NeedleworkTypes { get; set; }
        public virtual DbSet<OrderCompositions> OrderCompositions { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<PaymentStatuses> PaymentStatuses { get; set; }
        public virtual DbSet<PickUpPoints> PickUpPoints { get; set; }
        public virtual DbSet<ProcessingStatuses> ProcessingStatuses { get; set; }
        public virtual DbSet<ProductAccessoryTypes> ProductAccessoryTypes { get; set; }
        public virtual DbSet<ProductNeedleworkTypes> ProductNeedleworkTypes { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<ProductStitchTypes> ProductStitchTypes { get; set; }
        public virtual DbSet<ProductThemes> ProductThemes { get; set; }
        public virtual DbSet<ProductTypes> ProductTypes { get; set; }
        public virtual DbSet<ReceivingStatuses> ReceivingStatuses { get; set; }
        public virtual DbSet<Reviews> Reviews { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<StitchTypes> StitchTypes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Themes> Themes { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
