//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeedleworkStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductAccessoryTypes
    {
        public int ProductAccessoryTypeID { get; set; }
        public int ProductID { get; set; }
        public int AccessoryTypeID { get; set; }
    
        public virtual AccessoryTypes AccessoryTypes { get; set; }
        public virtual Products Products { get; set; }
    }
}
