//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NeedleworkStore.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Carts = new HashSet<Carts>();
            this.Favourities = new HashSet<Favourities>();
            this.OrderCompositions = new HashSet<OrderCompositions>();
            this.ProductAccessoryTypes = new HashSet<ProductAccessoryTypes>();
            this.ProductNeedleworkTypes = new HashSet<ProductNeedleworkTypes>();
            this.ProductStitchTypes = new HashSet<ProductStitchTypes>();
            this.ProductThemes = new HashSet<ProductThemes>();
            this.Reviews = new HashSet<Reviews>();
        }
    
        public int ProductID { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> ProductPrice { get; set; }
        public string Description { get; set; }
        public string ProductImage { get; set; }
        public string ImagePath
        {
            get
            {
                if (String.IsNullOrEmpty(ProductImage) || String.IsNullOrWhiteSpace(ProductImage))
                    return "/ResImages/KlartLavandadlyanee.jpg";
                else
                    return "/ProdImages/" + ProductImage;
            }
        }
        public int DesignerID { get; set; }
        public int ProductTypeID { get; set; }
        public int AvailabilityStatusID { get; set; }
        public string QRLink { get; set; }
    
        public virtual AvailabilityStatuses AvailabilityStatuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carts> Carts { get; set; }
        public virtual Designers Designers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Favourities> Favourities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCompositions> OrderCompositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductAccessoryTypes> ProductAccessoryTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductNeedleworkTypes> ProductNeedleworkTypes { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductStitchTypes> ProductStitchTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductThemes> ProductThemes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reviews> Reviews { get; set; }
    }
}
